### ISSUE TITLE
AVZ incompatibility with new KVS

### ISSUE THREAD

**Issue by yashrk** [synrc/avz#17]
Keys in new KVS version must be integers; but in AVZ they aren't. So AVZ probably won't work with the new versions of KVS.

**Comment by fycth** [comment]
Fixed by the last commit. When using AVZ in your application, in `sys.config` you should use now **avz_user** table instead of **kvs_user**:

`{kvs, [{dba,store_mnesia}, {schema,[avz_user,kvs_acl,kvs_feed,kvs_subscription]}]},`

**Comment by yashrk** [comment]
Thank you!
