### ISSUE TITLE
avz_user.hrl - argument mismatch for macro 'ITERATOR'

### ISSUE THREAD

**Issue by Spoowy** [synrc/avz#19]
When attempting to make https://github.com/synrc/skyline, I get the following error output at AVZ's section:

`compiled src/avz_app.erl
/skyline/deps/avz/src/avz_sup.erl:4: Warning: export_all flag enabled - all functions will be exported
Compiled src/avz_sup.erl
Compiled src/avz_validator.erl
/skyline/deps/avz/include/avz_user.hrl:7: argument mismatch for macro 'ITERATOR'
/skyline/deps/avz/src/avz_user.erl:10: record avz_user undefined
/skyline/deps/avz/src/avz_user.erl:5: Warning: export_all flag enabled - all functions will be exported
ERROR: compile failed while processing /skyline/deps/avz: rebar_abort
make: *** [compile] Error 1`

Erlang version: 20.1

Contents of avz_app.erl:
`-ifndef(AVZ_USER_HRL).
-define(AVZ_USER_HRL, true).

-include_lib("kvs/include/kvs.hrl").

-record(avz_user,
        {?ITERATOR(feed, true),
         email,
         username,
         password,
         display_name,
         register_date,
         tokens = [],
         images,
         names,
         surnames,
         birth,
         sex,
         date,
         status,
         zone,
         type,
         comments = []
        }).

-endif.`

**Comment by 5HT** [comment]
Skyline is way old and is not compatible with current versions of N2O.

**Comment by Spoowy** [comment]
Thanks @5HT for your fast reply. That clears up some things for me. There were also issues with having it connect to websockets so I'm glad to hear that my mac is innocent.

Are there alternatives you could point me to, for learning N2O? I've read the No Bullshit Framework PDF already.

Cheers,
Erwin
